name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 15"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=visionOS Simulator,name=Apple Vision Pro"
          - "platform=watchOS Simulator,name=Apple Watch Series 6 (40mm)"
          - "platform=macOS,variant=Mac Catalyst"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme NSUI -destination "${{ matrix.destination }}" test | xcbeautify

  linux_test:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install swiftly
        run: curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash -s -- -y
      - name: Install the latest Swift toolchain
        run: swiftly install latest
      - name: Test
        run: swift test --enable-experimental-swift-testing
